name: user-in-team

on:
  pull_request:
    paths:
      - user-in-team/src/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-in-team
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout repo where the branch is coming from (i.e. forks) that
          # way we commit build changes to the correct repo/branch
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rebuild user-in-team
          commit_user_name: Conda Bot
          commit_user_email: conda-bot@users.noreply.github.com
          commit_author: Conda Bot <conda-bot@users.noreply.github.com>
